name: inventario_proyecto
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  http: ^1.3.0
  firebase_core: ^3.12.1
  cloud_firestore: ^5.6.5
  dio: ^5.8.0+1
  flutter_smart_dialog: ^4.9.8+7
  image_picker: ^1.1.2
  firebase_auth: ^5.5.1
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  firebase_messaging: ^15.2.5
  change_app_package_name: ^1.5.0
  excel: ^4.0.6
  intl: ^0.19.0
  permission_handler: ^12.0.1
  flutter_localization: ^0.3.3
  flutter_native_splash: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/icon/

# ðŸ”¹ ConfiguraciÃ³n del Ã­cono de la app
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

# ðŸ”¹ ConfiguraciÃ³n del splash screen
flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/icon/icon.png"
  android: true
  ios: true
